services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest

    ports:
      - "8333:8333"
      - "8888:8888"
      - "9333:9333"
      - "23646:23646"
    
    volumes:
      - ./data/seaweedfs_str/:/data

    env_file: .env
    restart: unless-stopped
  
  seaweedfs-remotesync:
    image: chrislusf/seaweedfs:latest
    depends_on:
      - seaweedfs
    command: ["filer.remote.sync", "-filer=seaweedfs:8888", "-dir=/upload/MGS"]
    restart: unless-stopped
